# Generated by Django 4.2.15 on 2024-08-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasteLock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_field', models.TextField()),
                ('password_field', models.CharField(max_length=100)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
    ]
