# Generated by Django 4.2.15 on 2024-08-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastelockly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastelock',
            name='password_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
