# Generated by Django 4.2.15 on 2024-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastelockly', '0002_alter_pastelock_password_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastelock',
            name='password_field',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
